local _, ns = ...
L = {}
ns.L = L

ns.locale = GetLocale()

ns.realm = GetNormalizedRealmName() -- On a fresh login this will return null
ns.oceania = { AmanThul = true, Barthilas = true, Caelestrasz = true, DathRemar = true,
			Dreadmaul = true, Frostmourne = true, Gundrak = true, JubeiThos = true, 
			Khazgoroth = true, Nagrand = true, Saurfang = true, Thaurissan = true,
			-- The following are Classic 1.15.x
			Yojamba = true, Remulos = true, Arugal = true, Felstriker = true,
			-- The following are Seasonal Classic 1.15.x
			Penance = true, Shadowstrike = true }
if ns.oceania[ ns.realm ] then
	ns.locale = "enGB"
end

setmetatable( L, { __index = function( L, key ) return key end } )

-- Firstly, translations I often use in all my AddOns

if ns.locale == "deDE" then
	ns.L["Character"] = "Charakter"
	ns.L["Account"] = "Accountweiter"
	ns.L["Completed"] = "Abgeschlossen"
	ns.L["Not Completed"] = "Nicht Abgeschlossen"
	ns.L["Options"] = "Optionen"
	ns.L["Map Pin Size"] = "Pin-Größe"
	ns.L["The Map Pin Size"] = "Die Größe der Karten-Pins"
	ns.L["Map Pin Alpha"] = "Kartenpin Alpha"
	ns.L["The alpha transparency of the map pins"] = "Die Alpha-Transparenz der Karten-Pins"
	ns.L["Show Coordinates"] = "Koordinaten anzeigen"
	ns.L["Show Coordinates Description"] = "Zeigen sie die koordinaten in QuickInfos auf "
		.."der Weltkarte und auf der Minikarte an"
	ns.L["Map Pin Selections"] = "Karten-Pin-Auswahl"
	ns.L["Gold"] = "Gold"
	ns.L["Red"] = "Rot"
	ns.L["Blue"] = "Blau"
	ns.L["Green"] = "Grün"
	ns.L["Ring"] = "Ring"
	ns.L["Cross"] = "Kreuz"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Frost"
	ns.L["Cogwheel"] = "Zahnrad"
	ns.L["White"] = "Weiß"
	ns.L["Purple"] = "Lila"
	ns.L["Yellow"] = "Gelb"
	ns.L["Grey"] = "Grau"
	ns.L["Mana Orb"] = "Manakugel"
	ns.L["Phasing"] = "Synchronisieren"
	ns.L["Raptor egg"] = "Raptor-Ei"
	ns.L["Stars"] = "Sternen"
	ns.L["Screw"] = "Schraube"
	ns.L["Left"] = "Links"
	ns.L["Right"] = "Rechts"
	ns.L["Try later"] = "Derzeit nicht möglich. Versuche es späte"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["Character"] = "Personaje"
	ns.L["Account"] = "la Cuenta"
	ns.L["Completed"] = "Completado"
	ns.L["Not Completed"] = ( ns.locale == "esES" ) and "Sin Completar" or "Incompleto"
	ns.L["Options"] = "Opciones"
	ns.L["Map Pin Size"] = "Tamaño de alfiler"
	ns.L["The Map Pin Size"] = "Tamaño de los pines del mapa"
	ns.L["Map Pin Alpha"] = "Alfa de los pines del mapa"
	ns.L["The alpha transparency of the map pins"] = "La transparencia alfa de los pines del mapa"
	ns.L["Show Coordinates"] = "Mostrar coordenadas"
	ns.L["Show Coordinates Description"] = "Mostrar coordenadas en información sobre "
		.."herramientas en el mapa del mundo y en el minimapa"
	ns.L["Map Pin Selections"] = "Selecciones de pines de mapa"
	ns.L["Gold"] = "Oro"
	ns.L["Red"] = "Rojo"
	ns.L["Blue"] = "Azul"
	ns.L["Green"] = "Verde"
	ns.L["Ring"] = "Anillo"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Escarcha"
	ns.L["Cogwheel"] = "Rueda dentada"
	ns.L["White"] = "Blanco"
	ns.L["Purple"] = "Púrpura"
	ns.L["Yellow"] = "Amarillo"
	ns.L["Grey"] = "Gris"
	ns.L["Mana Orb"] = "Orbe de maná"
	ns.L["Phasing"] = "Sincronización"	
	ns.L["Raptor egg"] = "Huevo de raptor"	
	ns.L["Stars"] = "Estrellas"
	ns.L["Screw"] = "Tornillo"
	ns.L["Left"] = "Izquierda"
	ns.L["Right"] = "Derecha"
	ns.L["Try later"] = "No es posible en este momento. Intenta más tarde"

elseif ns.locale == "frFR" then
	ns.L["Character"] = "Personnage"
	ns.L["Account"] = "le Compte"
	ns.L["Completed"] = "Achevé"
	ns.L["Not Completed"] = "Non achevé"
	ns.L["Options"] = "Options"
	ns.L["Map Pin Size"] = "Taille des épingles"
	ns.L["The Map Pin Size"] = "La taille des épingles de carte"
	ns.L["Map Pin Alpha"] = "Alpha des épingles de carte"
	ns.L["The alpha transparency of the map pins"] = "La transparence alpha des épingles de la carte"
	ns.L["Show Coordinates"] = "Afficher les coordonnées"
	ns.L["Show Coordinates Description"] = "Afficher les coordonnées\124r dans les info-bulles sur "
		.."la carte du monde et la mini-carte"
	ns.L["Map Pin Selections"] = "Sélections de broches de carte"
	ns.L["Gold"] = "Or"
	ns.L["Red"] = "Rouge"
	ns.L["Blue"] = "Bleue"
	ns.L["Green"] = "Vert"
	ns.L["Ring"] = "Bague"
	ns.L["Cross"] = "Traverser"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Givre"
	ns.L["Cogwheel"] = "Roue dentée"
	ns.L["White"] = "Blanc"
	ns.L["Purple"] = "Violet"
	ns.L["Yellow"] = "Jaune"
	ns.L["Grey"] = "Gris"
	ns.L["Mana Orb"] = "Orbe de mana"
	ns.L["Phasing"] = "Synchronisation"
	ns.L["Raptor egg"] = "Œuf de Rapace"
	ns.L["Stars"] = "Étoiles"
	ns.L["Screw"] = "Vis"
	ns.L["Left"] = "Gauche"
	ns.L["Right"] = "Droite"
	ns.L["Try later"] = "Pas possible pour le moment. Essayer plus tard"

elseif ns.locale == "itIT" then
	ns.L["Character"] = "Personaggio"
	ns.L["Account"] = "Account"
	ns.L["Completed"] = "Completo"
	ns.L["Not Completed"] = "Non Compiuto"
	ns.L["Options"] = "Opzioni"
	ns.L["Map Pin Size"] = "Dimensione del pin"
	ns.L["The Map Pin Size"] = "La dimensione dei Pin della mappa"
	ns.L["Map Pin Alpha"] = "Mappa pin alfa"
	ns.L["The alpha transparency of the map pins"] = "La trasparenza alfa dei pin della mappa"
	ns.L["Show Coordinates"] = "Mostra coordinate"
	ns.L["Show Coordinates Description"] = "Visualizza le coordinate\124r nelle descrizioni "
		.."comandi sulla mappa del mondo e sulla minimappa"
	ns.L["Map Pin Selections"] = "Selezioni pin mappa"
	ns.L["Gold"] = "Oro"
	ns.L["Red"] = "Rosso"
	ns.L["Blue"] = "Blu"
	ns.L["Green"] = "Verde"
	ns.L["Ring"] = "Squillo"
	ns.L["Cross"] = "Attraverso"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gelo"
	ns.L["Cogwheel"] = "Ruota dentata"
	ns.L["White"] = "Bianca"
	ns.L["Purple"] = "Viola"
	ns.L["Yellow"] = "Giallo"
	ns.L["Grey"] = "Grigio"
	ns.L["Mana Orb"] = "Globo di Mana"
	ns.L["Phasing"] = "Sincronizzazione"
	ns.L["Raptor egg"] = "Raptor Uovo"
	ns.L["Stars"] = "Stelle"
	ns.L["Screw"] = "Vite"
	ns.L["Left"] = "Sinistra"
	ns.L["Right"] = "Destra"
	ns.L["Try later"] = "Non è possibile in questo momento. Prova più tardi"

elseif ns.locale == "koKR" then
	ns.L["Character"] = "캐릭터"
	ns.L["Account"] = "계정"
	ns.L["Completed"] = "완료"
	ns.L["Not Completed"] = "미완료"
	ns.L["Options"] = "설정"
	ns.L["Map Pin Size"] = "지도 핀의 크기"
	ns.L["The Map Pin Size"] = "지도 핀의 크기"
	ns.L["Map Pin Alpha"] = "지도 핀의 알파"
	ns.L["The alpha transparency of the map pins"] = "지도 핀의 알파 투명도"
	ns.L["Show Coordinates"] = "좌표 표시"
	ns.L["Show Coordinates Description"] = "세계지도 및 미니지도의 도구 설명에 좌표를 표시합니다."
	ns.L["Map Pin Selections"] = "지도 핀 선택"
	ns.L["Gold"] = "금"
	ns.L["Red"] = "빨간"
	ns.L["Blue"] = "푸른"
	ns.L["Green"] = "녹색"
	ns.L["Ring"] = "반지"
	ns.L["Cross"] = "십자가"
	ns.L["Diamond"] = "다이아몬드"
	ns.L["Frost"] = "냉기"
	ns.L["Cogwheel"] = "톱니 바퀴"
	ns.L["White"] = "화이트"
	ns.L["Purple"] = "보라색"
	ns.L["Yellow"] = "노랑"
	ns.L["Grey"] = "회색"
	ns.L["Mana Orb"] = "마나 보주"
	ns.L["Phasing"] = "동기화 중"
	ns.L["Raptor egg"] = "랩터의 알"
	ns.L["Stars"] = "별"
	ns.L["Screw"] = "나사"
	ns.L["Left"] = "왼쪽"
	ns.L["Right"] = "오른쪽"
	ns.L["Try later"] = "지금은 불가능합니다. 나중에 시도하세요"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["Character"] = "Personagem"
	ns.L["Account"] = "à Conta"
	ns.L["Completed"] = "Concluído"
	ns.L["Not Completed"] = "Não Concluído"
	ns.L["Options"] = "Opções"
	ns.L["Map Pin Size"] = "Tamanho do pino"
	ns.L["The Map Pin Size"] = "O tamanho dos pinos do mapa"
	ns.L["Map Pin Alpha"] = "Alfa dos pinos do mapa"
	ns.L["The alpha transparency of the map pins"] = "A transparência alfa dos pinos do mapa"
	ns.L["Show Coordinates"] = "Mostrar coordenadas"
	ns.L["Show Coordinates Description"] = "Exibir coordenadas\124r em dicas de ferramentas "
		.."no mapa mundial e no minimapa"
	ns.L["Map Pin Selections"] = "Seleções de pinos de mapa"
	ns.L["Gold"] = "Ouro"
	ns.L["Red"] = "Vermelho"
	ns.L["Blue"] = "Azul"
	ns.L["Green"] = "Verde"
	ns.L["Ring"] = "Anel"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gélido"
	ns.L["Cogwheel"] = "Roda dentada"
	ns.L["White"] = "Branco"
	ns.L["Purple"] = "Roxa"
	ns.L["Yellow"] = "Amarelo"
	ns.L["Grey"] = "Cinzento"
	ns.L["Mana Orb"] = "Orbe de Mana"
	ns.L["Phasing"] = "Sincronização"
	ns.L["Raptor egg"] = "Ovo de raptor"
	ns.L["Stars"] = "Estrelas"
	ns.L["Screw"] = "Parafuso"
	ns.L["Left"] = "Esquerda"
	ns.L["Right"] = "Direita"
	ns.L["Try later"] = "Não é possível neste momento. Tente depois"

elseif ns.locale == "ruRU" then
	ns.L["Character"] = "Персонажа"
	ns.L["Account"] = "Счет"
	ns.L["Completed"] = "Выполнено"
	ns.L["Not Completed"] = "Не Выполнено"
	ns.L["Options"] = "Параметры"
	ns.L["Map Pin Size"] = "Размер булавки"
	ns.L["The Map Pin Size"] = "Размер булавок на карте"
	ns.L["Map Pin Alpha"] = "Альфа булавок карты"
	ns.L["The alpha transparency of the map pins"] = "Альфа-прозрачность булавок карты"
	ns.L["Show Coordinates"] = "Показать Координаты"
	ns.L["Show Coordinates Description"] = "Отображает координаты\124r во всплывающих "
		.."подсказках на карте мира и мини-карте"
	ns.L["Map Pin Selections"] = "Выбор булавки карты"
	ns.L["Gold"] = "Золото"
	ns.L["Red"] = "Красный"
	ns.L["Blue"] = "Синий"
	ns.L["Green"] = "Зеленый"
	ns.L["Ring"] = "Звенеть"
	ns.L["Cross"] = "Крест"
	ns.L["Diamond"] = "Ромб"
	ns.L["Frost"] = "Лед"
	ns.L["Cogwheel"] = "Зубчатое колесо"
	ns.L["White"] = "белый"
	ns.L["Purple"] = "Пурпурный"
	ns.L["Yellow"] = "Желтый"
	ns.L["Grey"] = "Серый"
	ns.L["Mana Orb"] = "Cфера маны"
	ns.L["Phasing"] = "Синхронизация"
	ns.L["Raptor egg"] = "Яйцо ящера"
	ns.L["Stars"] = "Звезды"
	ns.L["Screw"] = "Винт"
	ns.L["Left"] = "Налево"
	ns.L["Right"] = "Направо"
	ns.L["Try later"] = "В настоящее время это невозможно. Попробуй позже"

elseif ns.locale == "zhCN" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "账号"
	ns.L["Completed"] = "已完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Options"] = "选项"
	ns.L["Map Pin Size"] = "地图图钉的大小"
	ns.L["The Map Pin Size"] = "地图图钉的大小"
	ns.L["Map Pin Alpha"] = "地图图钉的透明度"
	ns.L["The alpha transparency of the map pins"] = "地图图钉的透明度"
	ns.L["Show Coordinates"] = "显示坐标"
	ns.L["Show Coordinates Description"] = "在世界地图和迷你地图上的工具提示中显示坐标"
	ns.L["Map Pin Selections"] = "地图图钉选择"
	ns.L["Gold"] = "金子"
	ns.L["Red"] = "红"
	ns.L["Blue"] = "蓝"
	ns.L["Green"] = "绿色"
	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "冰霜"
	ns.L["Cogwheel"] = "齿轮"
	ns.L["White"] = "白色"
	ns.L["Purple"] = "紫色"
	ns.L["Yellow"] = "黄色"
	ns.L["Grey"] = "灰色"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor egg"] = "迅猛龙蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "拧"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Try later"] = "目前不可能。稍后再试"

elseif ns.locale == "zhTW" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "賬號"
	ns.L["Completed"] = "完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Options"] = "選項"
	ns.L["Map Pin Size"] = "地圖圖釘的大小"
	ns.L["The Map Pin Size"] = "地圖圖釘的大小"
	ns.L["Map Pin Alpha"] = "地圖圖釘的透明度"
	ns.L["The alpha transparency of the map pins"] = "地圖圖釘的透明度"
	ns.L["Show Coordinates"] = "顯示坐標"
	ns.L["Show Coordinates Description"] = "在世界地圖和迷你地圖上的工具提示中顯示坐標"
	ns.L["Map Pin Selections"] = "地圖圖釘選擇"
	ns.L["Gold"] = "金子"
	ns.L["Red"] = "紅"
	ns.L["Blue"] = "藍"
	ns.L["Green"] = "綠色"
	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "霜"
	ns.L["Cogwheel"] = "齒輪"
	ns.L["White"] = "白色"
	ns.L["Purple"] = "紫色"
	ns.L["Yellow"] = "黃色"
	ns.L["Grey"] = "灰色"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor egg"] = "迅猛龍蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "擰"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Try later"] = "目前不可能。稍後再試"

else
	ns.L["Character"] = "Character"
	ns.L["Account"] = "Account"
	ns.L["Completed"] = "Completed"
	ns.L["Not Completed"] = "Not Completed"
	ns.L["Options"] = "Options"
	ns.L["Map Pin Size"] = "Map Pin Size"
	ns.L["The Map Pin Size"] = "The Map Pin Size"
	ns.L["Map Pin Alpha"] = "Map Pin Alpha"
	ns.L["The alpha transparency of the map pins"] = "The alpha transparency of the map pins"
	ns.L["Show Coordinates"] = "Show Coordinates"
	ns.L["Show Coordinates Description"] = "Display coordinates in tooltips on the world map and the mini map"
	ns.L["Map Pin Selections"] = "Map Pin Selections"
	ns.L["Gold"] = "Gold"
	ns.L["Red"] = "Red"
	ns.L["Blue"] = "Blue"
	ns.L["Green"] = "Green"
	ns.L["Ring"] = "Ring"
	ns.L["Cross"] = "Cross"
	ns.L["Diamond"] = "Diamond"
	ns.L["Frost"] = "Frost"
	ns.L["Cogwheel"] = "Cogwheel"
	ns.L["White"] = "White"
	ns.L["Purple"] = "Purple"
	ns.L["Yellow"] = "Yellow"
	ns.L["Grey"] = ( ( ns.locale == "enUS" ) and "Gray" or "Grey" )
	ns.L["Mana Orb"] = "Mana Orb"
	ns.L["Phasing"] = "Phasing"
	ns.L["Raptor egg"] = "Raptor egg"
	ns.L["Stars"] = "Stars"
	ns.L["Screw"] = "Screw"
	ns.L["Left"] = "Left"
	ns.L["Right"] = "Right"
	ns.L["Try later"] = "Not possible at this time. Try later"
end

-- Translations specific to the Chests AddOn

if ns.locale == "deDE" then
	ns.L["AddOn Description"] = "Alle ramponierten Truhen"
	ns.L["AoPD"] = "Aura des paralysierenden Schreckens"
	ns.L["Battered Chest"] = "Ramponierte Truhe"
	ns.L["Best Hunter Pets"] = "Beste Jägerhaustiere"
	ns.L["Chest Rank"] = "Der Rang der Truhe: "
	ns.L["Cozy Sleeping Bag"] = "Gemütlicher Schlafsack"
	ns.L["Fel Portal"] = "Teufelsportal "
	ns.L["Nightmare"] = "Alptraum"
	ns.L["Priest"] = "Priester"
	ns.L["Void Touched"] = "Leerenberührte"
	
elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["AddOn Description"] = "Todos los cofres maltratados"
	ns.L["AoPD"] = "Aura de terror paralizante"
	ns.L["Battered Chest"] = "Cofre maltrecho"
	ns.L["Best Hunter Pets"] = "Mascotas de cazador"
	ns.L["Chest Rank"] = "Rango de cofre: "
	ns.L["Cozy Sleeping Bag"] = "Saco de dormir acogedor"
	ns.L["Fel Portal"] = "Portal vil"
	ns.L["Nightmare"] = "Pesadilla"
	ns.L["Priest"] = "Sacerdote"
	ns.L["Void Touched"] = "Tocados por el Vacío"

elseif ns.locale == "frFR" then
	ns.L["AddOn Description"] = "Tous les coffres battus"
	ns.L["AoPD"] = "Aura d’effroi paralysant"
	ns.L["Battered Chest"] = "Coffre endommagé"
	ns.L["Best Hunter Pets"] = "Meilleurs mascotte de cazador"
	ns.L["Chest Rank"] = "Rang du coffre: "
	ns.L["Cozy Sleeping Bag"] = "Sac de couchage douillet"
	ns.L["Fel Portal"] = "Portail gangrené"
	ns.L["Nightmare"] = "Cauchemar"
	ns.L["Priest"] = "Prêtre"
	ns.L["Void Touched"] = "Touché par le Vide"

elseif ns.locale == "koKR" then
	ns.L["AddOn Description"] = "모든 낡은 궤짝"
	ns.L["AoPD"] = "마비의 공포 오라"
	ns.L["Battered Chest"] = "낡은 궤짝"
	ns.L["Best Hunter Pets"] = "최고의 사냥꾼 야수"
	ns.L["Chest Rank"] = "가슴 순위: "
	ns.L["Cozy Sleeping Bag"] = "아늑한 침낭"
	ns.L["Fel Portal"] = "지옥 차원문"
	ns.L["Gnomeregan"] = "놈리건"
	ns.L["Nightmare"] = "악몽"
	ns.L["Priest"] = "사제"
	ns.L["Void Touched"] = "공허에 물든"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["AddOn Description"] = "Todos os Baús Desgastado"
	ns.L["AoPD"] = "Aura de Horror Paralisante"
	ns.L["Battered Chest"] = "Baú Desgastado"
	ns.L["Best Hunter Pets"] = "Os melhores Ajudante de Caçador"
	ns.L["Chest Rank"] = "Classificação do baú: "
	ns.L["Fel Portal"] = "Portal Vil"
	ns.L["Gnomeregan"] = "Гномреган"
	ns.L["Nightmare"] = "Pesadelo"
	ns.L["Priest"] = "Sacerdote"
	ns.L["Void Touched"] = "Tocadas pelo Caos"

elseif ns.locale == "ruRU" then
	ns.L["AddOn Description"] = "Все Побитые сундукии"
	ns.L["AoPD"] = "Аура парализующего ужаса"
	ns.L["Battered Chest"] = "Побитый сундук"
	ns.L["Best Hunter Pets"] = "Лучшие питомцы для охотников"
	ns.L["Chest Rank"] = "Ранг Сундука: "
	ns.L["Cozy Sleeping Bag"] = "Уютный спальный мешок"
	ns.L["Fel Portal"] = "Портал Скверны"
	ns.L["Gnomeregan"] = "Гномреган"
	ns.L["Nightmare"] = "Кошмар"
	ns.L["Priest"] = "Жрец"
	ns.L["Void Touched"] = "Меченные Бездной"

elseif ns.locale == "zhCN" then
	ns.L["AddOn Description"] = "所有破损的箱子"
	ns.L["AoPD"] = "痹体恐惧氛围"
	ns.L["Battered Chest"] = "破损的箱子"
	ns.L["Best Hunter Pets"] = "最佳猎人宠物"
	ns.L["Chest Rank"] = "宝箱的等级: "
	ns.L["Fel Portal"] = "邪能传送门"
	ns.L["Gnomeregan"] = "诺莫瑞根"
	ns.L["Nightmare"] = "恶梦"
	ns.L["Priest"] = "牧师"
	ns.L["Void Touched"] = "虚空触动"

elseif ns.locale == "zhTW" then
	ns.L["AddOn Description"] = "所有破損的箱子"
	ns.L["AoPD"] = "麻痺體恐懼氛圍"
	ns.L["Battered Chest"] = "破損的箱子"
	ns.L["Best Hunter Pets"] = "最佳獵人寵物"
	ns.L["Chest Rank"] = "寶箱的等級: "
	ns.L["Fel Portal"] = "邪能傳送門"
	ns.L["Gnomeregan"] = "諾莫瑞根"
	ns.L["Nightmare"] = "惡夢"
	ns.L["Priest"] = "牧師"
	ns.L["Void Touched"] = "虛空觸動"

else
	ns.L["AddOn Description"] = "Helps you to collect Battered Chests"
	ns.L["AoPD"] = "Aura of Paralyzing Dread"
	ns.L["Chest Rank"] = "Chest Rank: "
	ns.L["Void Touched"] = "Void-Touched"
end

-- Textures

if ns.locale == "deDE" then
	ns.L["Adrenaline"] = "Adrenalin"
	ns.L["Arcane"] = "Arkane"
	ns.L["Demonic"] = "Dämonische"
	ns.L["Duty"] = "Pflicht"
	ns.L["Frozen"] = "Gefroren"
elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["Adrenaline"] = "Adrenalina"
	ns.L["Arcane"] = "Arcana"
	ns.L["Demonic"] = "Demoníaca"
	ns.L["Duty"] = "Deber"
	ns.L["Frozen"] = "Congelado"
elseif ns.locale == "frFR" then
	ns.L["Adrenaline"] = "Adrénaline"
	ns.L["Arcane"] = "Arcanes"
	ns.L["Demonic"] = "Démoniaque"
	ns.L["Duty"] = "Devoir"
	ns.L["Frozen"] = "Gelé"
elseif ns.locale == "koKR" then
	ns.L["Adrenaline"] = "아드레날린"
	ns.L["Arcane"] = "비전"
	ns.L["Demonic"] = "악마의"
	ns.L["Duty"] = "의무"
	ns.L["Frozen"] = "언"
elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["Adrenaline"] = "Adrenalina"
	ns.L["Arcane"] = "Arcana"
	ns.L["Demonic"] = "Demoníaca"
	ns.L["Duty"] = "Dever"
	ns.L["Frozen"] = "Congelado"
elseif ns.locale == "ruRU" then
	ns.L["Adrenaline"] = "Адреналин"
	ns.L["Arcane"] = "Чародейская"
	ns.L["Demonic"] = "Демоническая"
	ns.L["Duty"] = "долга"
	ns.L["Frozen"] = "Замороженный"
elseif ns.locale == "zhCN" then
	ns.L["Adrenaline"] = "肾上腺素"
	ns.L["Arcane"] = "奥术"
	ns.L["Demonic"] = "恶魔"
	ns.L["Duty"] = "义务"
	ns.L["Frozen"] = "冷冻"
elseif ns.locale == "zhTW" then
	ns.L["Adrenaline"] = "腎上腺素"
	ns.L["Arcane"] = "奧術"
	ns.L["Demonic"] = "惡魔"
	ns.L["Duty"] = "義務"
	ns.L["Frozen"] = "冷凍"
end

-- v1.09+ Quest Names

if ns.locale == "deDE" then
	ns.L["...and that note you found"] = "...und diese Notiz, die Ihr gefunden habt." -- The period is in the translation
	ns.L["A Fortuitous Turn of Events"] = "Eine zufällige Wende der Ereignisse"
	ns.L["An Amalgamation of Nightmares"] = "Eine Verschmelzung von Alpträumen"
	ns.L["Eagle's Fist"] = "Adlerfaust"
	ns.L["Going Under"] = "Untergehen"
	ns.L["Return to Moonglade"] = "Kehrt nach Moonglade zurück"
	ns.L["Salvaging the Salvagematic"] = "Wiederverwertung des Wiederverwertungsmats"
	ns.L["Scramble"] = "Weg hier"
	ns.L["Secrets of Elune (1)"] = "Geheimnisse von Elune (1)"
	ns.L["Secrets of Elune (2)"] = "Geheimnisse von Elune (2)"
	ns.L["Secrets of the Light (1)"] = "Geheimnisse des Lichts (1)"
	ns.L["Secrets of the Light (2)"] = "Geheimnisse des Lichts (2)"
	ns.L["Secrets of the Loa (1)"] = "Geheimnisse der Loa (1)"
	ns.L["Secrets of the Loa (2)"] = "Geheimnisse der Loa (2)"
	ns.L["Secrets of Undeath (1)"] = "Geheimnisse des Untodes (1)"
	ns.L["Secrets of Undeath (2)"] = "Geheimnisse des Untodes (2)"
	ns.L["Shifting Scale Talisman"] = "Veränderlicher Schuppentalisman"
	ns.L["Stepping Stones"] = "Trittsteine"
	ns.L["The Bad News..."] = "Die schlechte Nachricht..."
	ns.L["The Corroded Core"] = "Der korrodierte Kern"
	ns.L["The Lost Vambraces"] = "Die verlorenen Unterarmschienen"
	ns.L["The Salvagematic 9000!"] = "The Salvagematic 9000!"
	ns.L["This Must Be The Place"] = "Das muss der Ort sein"
	ns.L["Waking the Nightmare"] = "Den Alptraum schwächen"
	ns.L["Warranty Claim"] = "Garantieanspruch"
	ns.L["Wet Job"] = "Feuchte Angelegenheit"
elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["...and that note you found"] = "Y la nota que has encontrado..."
	ns.L["A Fortuitous Turn of Events"] = "Un giro casual de los acontecimientos"
	ns.L["An Amalgamation of Nightmares"] = "Una amalgama de pesadillas"
	ns.L["Eagle's Fist"] = "El puño del águila"
	ns.L["Going Under"] = "Al fango"
	ns.L["Quadrangulation"] = "Cuadrangulación"
	ns.L["Return to Moonglade"] = "Retorno a Claro de la Luna"
	ns.L["Salvaging the Salvagematic"] = "Recuperar el Reciclamatic"
	ns.L["Scramble"] = "Revolver"
	ns.L["Secrets of Elune (1)"] = "Secretos de Elune (1)"
	ns.L["Secrets of Elune (2)"] = "Secretos de Elune (2)"
	ns.L["Secrets of the Light (1)"] = "Secretos de la Luz (1)"
	ns.L["Secrets of the Light (2)"] = "Secretos de la Luz (2)"
	ns.L["Secrets of the Loa (1)"] = "Secretos de los loa (1)"
	ns.L["Secrets of the Loa (2)"] = "Secretos de los loa (2)"
	ns.L["Secrets of Undeath (1)"] = "Secretos de la no-muerte (1)"
	ns.L["Secrets of Undeath (2)"] = "Secretos de la no-muerte (2)"
	ns.L["Shifting Scale Talisman"] = "El dije de escamas cambiante"
	ns.L["Stepping Stones"] = "Peldaños"
	ns.L["The Bad News..."] = "Tengo malas noticias..."
	ns.L["The Corroded Core"] = "El núcleo corroído"
	ns.L["The Lost Vambraces"] = "Los avambrazos perdidos"
	ns.L["The Salvagematic 9000!"] = "¡El Reciclamatic 9000!"
	ns.L["This Must Be The Place"] = "Este debe de ser el lugar"
	ns.L["Waking the Nightmare"] = "El despertar de la Pesadilla"
	ns.L["Warranty Claim"] = "Reclamación de garantía"
	ns.L["Wet Job"] = "Un trabajo sucio"
elseif ns.locale == "frFR" then
	ns.L["...and that note you found"] = "… et cette note que vous avez trouvée"
	ns.L["A Fortuitous Turn of Events"] = "Un rebondissement plus qu’heureux"
	ns.L["An Amalgamation of Nightmares"] = "Un amalgame de cauchemars"
	ns.L["Eagle's Fist"] = "Le poing de l’aigle"
	ns.L["Going Under"] = "Plongée"
	ns.L["Return to Moonglade"] = "Retour à Reflet-de-Lune"
	ns.L["Salvaging the Salvagematic"] = "Recycle-o-Matic en panique"
	ns.L["Scramble"] = "Décaniller"
	ns.L["Secrets of Elune (1)"] = "Les secrets d’Élune (1)"
	ns.L["Secrets of Elune (2)"] = "Les secrets d’Élune (2)"
	ns.L["Secrets of the Light (1)"] = "Les secrets de la Lumière (1)"
	ns.L["Secrets of the Light (2)"] = "Les secrets de la Lumière (2)"
	ns.L["Secrets of the Loa (1)"] = "Les secrets des Loas (1)"
	ns.L["Secrets of the Loa (2)"] = "Les secrets des Loas (2)"
	ns.L["Secrets of Undeath (1)"] = "Les secrets de la non-mort (1)"
	ns.L["Secrets of Undeath (2)"] = "Les secrets de la non-mort (2)"
	ns.L["Shifting Scale Talisman"] = "Talisman d’écailles changeantes"
	ns.L["Stepping Stones"] = "Tort-tue"
	ns.L["The Bad News..."] = "La mauvaise nouvelle…"
	ns.L["The Corroded Core"] = "Le noyau rouillé"
	ns.L["The Lost Vambraces"] = "Les protège-bras perdus"
	ns.L["The Salvagematic 9000!"] = "Le Recycle-o-Matic 9000!"
	ns.L["This Must Be The Place"] = "Ça doit être ici"
	ns.L["Waking the Nightmare"] = "Réveiller le Cauchemar"
	ns.L["Warranty Claim"] = "Notice de garantie"
	ns.L["Wet Job"] = "Travail humide"
elseif ns.locale == "koKR" then
	ns.L["...and that note you found"] = "...그때 찾은 그 기록"
	ns.L["A Fortuitous Turn of Events"] = "행운의 반전"
	ns.L["An Amalgamation of Nightmares"] = "악몽의 융합체"
	ns.L["Eagle's Fist"] = "독수리의 주먹"
	ns.L["Going Under"] = "잠입"
	ns.L["Itharius"] = "이타리우스"
	ns.L["Quadrangulation"] = "사각 측량"
	ns.L["Return to Moonglade"] = "달숲으로"
	ns.L["Salvaging the Salvagematic"] = "수습기를 수습하는 방법"
	ns.L["Scramble"] = "허겁지겁"
	ns.L["Secrets of Elune (1)"] = "엘룬의 비밀 (1)" -- No in game translation
	ns.L["Secrets of Elune (2)"] = "엘룬의 비밀 (2)" -- No in game translation
	ns.L["Secrets of the Light (1)"] = "빛의 비밀 (1)" -- No in game translation
	ns.L["Secrets of the Light (2)"] = "빛의 비밀 (2)" -- No in game translation
	ns.L["Secrets of the Loa (1)"] = "로아의 비밀 (1)" -- No in game translation
	ns.L["Secrets of the Loa (2)"] = "로아의 비밀 (2)" -- No in game translation
	ns.L["Secrets of Undeath (1)"] = "불사의 비밀 (1)" -- No in game translation
	ns.L["Secrets of Undeath (2)"] = "불사의 비밀 (2)" -- No in game translation
	ns.L["Shifting Scale Talisman"] = "변화무쌍한 비늘 부적"
	ns.L["Stepping Stones"] = "디딤돌"
	ns.L["The Bad News..."] = "슬픈 소식..."
	ns.L["The Corroded Core"] = "부식된 핵"
	ns.L["The Lost Vambraces"] = "잃어버린 완갑" -- No in game translation
	ns.L["The Salvagematic 9000!"] = "자동 수습기 9000"
	ns.L["This Must Be The Place"] = "여기가 분명해"
	ns.L["Waking the Nightmare"] = "깨어나는 악몽"
	ns.L["Warranty Claim"] = "품질 보증"
	ns.L["Wet Job"] = "손 더럽히는 일"
elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["...and that note you found"] = "... e aquele bilhete, hein?"
	ns.L["A Fortuitous Turn of Events"] = "Uma reviravolta fortuita nos acontecimentos" -- No in game translation
	ns.L["An Amalgamation of Nightmares"] = "Pesadelos amalgamados"
	ns.L["Eagle's Fist"] = "Punho da Águia"
	ns.L["Going Under"] = "Sucumbindo"
	ns.L["Itharius"] = "Itharius" -- No in game translation
	ns.L["Quadrangulation"] = "Quadrangulação"
	ns.L["Return to Moonglade"] = "Voltar para Clareira da Lua" -- No in game translation
	ns.L["Salvaging the Salvagematic"] = "Recuperando o Recuperomático"
	ns.L["Scramble"] = "Rabisco"
	ns.L["Secrets of Elune (1)"] = "Segredos de Eluna (1)"
	ns.L["Secrets of Elune (2)"] = "Segredos de Eluna (2)"
	ns.L["Secrets of the Light (1)"] = "Segredos da Luz (1)" -- No in game translation
	ns.L["Secrets of the Light (2)"] = "Segredos da Luz (2)" -- No in game translation
	ns.L["Secrets of the Loa (1)"] = "Segredos dos Loa (1)" -- No in game translation
	ns.L["Secrets of the Loa (2)"] = "Segredos dos Loa (2)" -- No in game translation
	ns.L["Secrets of Undeath (1)"] = "Segredos da Morte-viva (1)" -- No in game translation
	ns.L["Secrets of Undeath (2)"] = "Segredos da Morte-viva (2)" -- No in game translation
	ns.L["Shifting Scale Talisman"] = "Talismã de Escama Cambiante"
	ns.L["Stepping Stones"] = "Degraus"
	ns.L["The Bad News..."] = "As más notícias..." -- No in game translation
	ns.L["The Corroded Core"] = "O núcleo corroído"
	ns.L["The Lost Vambraces"] = "Avambraços perdidos"
	ns.L["The Salvagematic 9000!"] = "O Recuperomático 9000!"
	ns.L["This Must Be The Place"] = "Deve ser aqui"
	ns.L["Waking the Nightmare"] = "Despertando o pesadelo"
	ns.L["Warranty Claim"] = "Reivindicação de garantia" -- No in game translation
	ns.L["Wet Job"] = "Trabalho suado"
elseif ns.locale == "ruRU" then
	ns.L["...and that note you found"] = "Загадочная записка"
	ns.L["A Fortuitous Turn of Events"] = "Случайный поворот событий" -- No in game translation
	ns.L["An Amalgamation of Nightmares"] = "Слияние Кошмаров"
	ns.L["Eagle's Fist"] = "Орлиный кулак"
	ns.L["Going Under"] = "Идя под" -- No in game translation
	ns.L["Itharius"] = "Итар"
	ns.L["Quadrangulation"] = "Квадрангуляция"
	ns.L["Return to Moonglade"] = "Вернитесь на Лунная поляна" -- No in game translation
	ns.L["Salvaging the Salvagematic"] = "Рано Утилитрону в утиль"
	ns.L["Scramble"] = "По тревоге"
	ns.L["Secrets of Elune (1)"] = "Таинства Элуны (1)"
	ns.L["Secrets of Elune (2)"] = "Таинства Элуны (2)"
	ns.L["Secrets of the Light (1)"] = "Таинства Света (1)"
	ns.L["Secrets of the Light (2)"] = "Таинства Света (2)"
	ns.L["Secrets of the Loa (1)"] = "Таинства лоа (1)"
	ns.L["Secrets of the Loa (2)"] = "Таинства лоа (2)"
	ns.L["Secrets of Undeath (1)"] = "Таинства Отрекшихся (1)"
	ns.L["Secrets of Undeath (2)"] = "Таинства Отрекшихся (2)"
	ns.L["Shifting Scale Talisman"] = "Талисман из изменчивой чешуи"
	ns.L["Stepping Stones"] = "Каменные ступени"
	ns.L["The Bad News..."] = "Плохие новости..." -- No in game translation
	ns.L["The Corroded Core"] = "Проржавевшее ядро"
	ns.L["The Lost Vambraces"] = "Потерянные наручи" -- No in game translation
	ns.L["The Salvagematic 9000!"] = "Утилитрон 9000"
	ns.L["This Must Be The Place"] = "Должно быть, это здесь"
	ns.L["Waking the Nightmare"] = "Пора просыпаться от кошмара"
	ns.L["Warranty Claim"] = "Претензия по гарантии" -- No in game translation
	ns.L["Wet Job"] = "Мокрая работа"
elseif ns.locale == "zhCN" then
	ns.L["...and that note you found"] = "……你所找到的纸条"
	ns.L["A Fortuitous Turn of Events"] = "峰回路转"
	ns.L["An Amalgamation of Nightmares"] = "梦魇的融合怪"
	ns.L["Eagle's Fist"] = "鹰拳" -- No in game translation
	ns.L["Going Under"] = "深入其中"
	ns.L["Itharius"] = "伊萨里奥斯" -- No in game translation
	ns.L["Quadrangulation"] = "四边定位"
	ns.L["Return to Moonglade"] = "返回月光林地"
	ns.L["Salvaging the Salvagematic"] = "回收器回收记"
	ns.L["Scramble"] = "抢" -- No in game translation
	ns.L["Secrets of Elune (1)"] = "艾露恩的秘密 (1)"
	ns.L["Secrets of Elune (2)"] = "艾露恩的秘密 (2)"
	ns.L["Secrets of the Light (1)"] = "圣光的秘密 (1)" -- No in game translation
	ns.L["Secrets of the Light (2)"] = "圣光的秘密 (2)" -- No in game translation
	ns.L["Secrets of the Loa (1)"] = "洛阿神灵的秘密 (1)" -- No in game translation
	ns.L["Secrets of the Loa (2)"] = "洛阿神灵的秘密 (2)" -- No in game translation
	ns.L["Secrets of Undeath (1)"] = "亡灵的秘密 (1)" -- No in game translation
	ns.L["Secrets of Undeath (2)"] = "亡灵的秘密 (2)" -- No in game translation
	ns.L["Shifting Scale Talisman"] = "幻变之鳞护符"
	ns.L["Stepping Stones"] = "垫脚石" -- No in game translation
	ns.L["The Bad News..."] = "坏消息是……"
	ns.L["The Corroded Core"] = "腐蚀的核心"
	ns.L["The Lost Vambraces"] = "失落的腕铠"
	ns.L["The Salvagematic 9000!"] = "超级回收器9000型！"
	ns.L["This Must Be The Place"] = "这一定是这个地方" -- No in game translation
	ns.L["Waking the Nightmare"] = "梦魇乍醒"
	ns.L["Warranty Claim"] = "保修索赔" -- No in game translation
	ns.L["Wet Job"] = "湿工作" -- No in game translation
elseif ns.locale == "zhTW" then
	ns.L["...and that note you found"] = "……你所找到的紙條"
	ns.L["A Fortuitous Turn of Events"] = "峰迴路轉"
	ns.L["An Amalgamation of Nightmares"] = "夢魘的融合怪"
	ns.L["Eagle's Fist"] = "鷹拳"
	ns.L["Going Under"] = "深入其中"
	ns.L["Itharius"] = "伊薩裡奧斯"
	ns.L["Quadrangulation"] = "四邊定位"
	ns.L["Return to Moonglade"] = "返回月光林地"
	ns.L["Salvaging the Salvagematic"] = "回收器回收記"
	ns.L["Scramble"] = "搶"
	ns.L["Secrets of Elune (1)"] = "艾露恩的秘密 (1)"
	ns.L["Secrets of Elune (2)"] = "艾露恩的秘密 (2)"
	ns.L["Secrets of the Light (1)"] = "聖光的秘密 (1)"
	ns.L["Secrets of the Light (2)"] = "聖光的秘密 (2)"
	ns.L["Secrets of the Loa (1)"] = "洛阿神靈的秘密 (1)"
	ns.L["Secrets of the Loa (2)"] = "洛阿神靈的秘密 (2)"
	ns.L["Secrets of Undeath (1)"] = "亡靈的秘密 (1)"
	ns.L["Secrets of Undeath (2)"] = "亡靈的秘密 (2)"
	ns.L["Shifting Scale Talisman"] = "幻變之鱗護符"
	ns.L["Stepping Stones"] = "墊腳石"
	ns.L["The Bad News..."] = "壞消息是…"
	ns.L["The Corroded Core"] = "腐蝕的核心"
	ns.L["The Lost Vambraces"] = "失落的腕鎧"
	ns.L["The Salvagematic 9000!"] = "超級回收器9000型！"
	ns.L["This Must Be The Place"] = "這一定是這個地方"
	ns.L["Waking the Nightmare"] = "夢魘乍醒"
	ns.L["Warranty Claim"] = "保固索賠"
	ns.L["Wet Job"] = "濕工作"
else
--	ns.L["An Amalgamation of Nightmares"] = "An Amalagamation of Nightmares" -- Do I use Blizzard's typo?
end